# Generated by Django 2.2.5 on 2019-09-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teh_challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserReg',
        ),
        migrations.RenameField(
            model_name='userreg',
            old_name='job_poaition',
            new_name='job_position',
        ),
    ]
