# Generated by Django 2.2.5 on 2019-09-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teh_challenge', '0002_auto_20190924_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='created_on',
        ),
    ]
